version: '3'
services:
  db:
    image: mongo:4.2.0-bionic  
    environment:
        MONGO_INITDB_DATABASE: test_gps_tracker
    ports:
        - 27018:27017
    restart: always
  gps-service:
    build: ./gps-service
    container_name: gps-service
    ports: 
        - 8087:8080
    environment:
        MONGO_HOST: db
        MONGO_PORT: 27017
        MONGO_INITDB_DATABASE: test_gps_tracker
    restart: always
    links:
        - db
  info-service:
    build: ./info-service
    container_name: info-service
    ports:
      - 8086:8080
    environment:
      GPS_SERVICE_URL: gps-service
      GPS_SERVICE_PORT: 8080
    restart: always
    links:
      - db
      - gps-service

# after that you can run the script 'wrk_load_testing_script.sh' in 'loadtesting' folder
    
           
        

