version: '3'
services:
  db:
    image: mongo:4.2.0-bionic  
    environment:
        MONGO_INITDB_DATABASE: test_gps_tracker
    ports:
        - 27018:27017
    restart: always
  gps-service:
    build: ./gps-service
    container_name: application
    ports: 
        - 8081:8080
    environment:
        MONGO_HOST: db
        MONGO_PORT: 27018
        MONGO_INITDB_DATABASE: test_gps_tracker
    restart: always
    links:
        - db
#  load-testing:
#    image: jordi/ab:latest
#    copy: './ab/ /opt/ab/'
#    volumes:
#        - /opt/ab/
#    working_dir: '/opt/ab/'
#    entrypoint:
#        - '/usr/bin/ab ab -T application/json -p ./post.json -v 2 http://gps-service/gps-tracker'
#    links:
#        - gps-service
    
           
        

