server:
  port: @server.port@
spring:
  profiles:
    active: @spring.profiles.active@
mongodb:
  insert_bulk_size: 20000

logging:
  level:
    com.github.evgeniymelnikov: debug
---
spring:
  profiles: dev
mongodb:
  host: localhost
  database: gps_tracker
  port: 27020

---
spring:
  profiles: dev-docker-compose
mongodb:
  host: ${MONGO_HOST}
  database: ${MONGO_INITDB_DATABASE}
  port: ${MONGO_PORT}
